#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Makoto Moriwaka <s20c1120he@s.chibakoudai.jp>
# SPDX-License-Idenifier: BSD-3-Clause

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)


